startGECKOproject()
obj.params.enzyme_comp = '';
adapterLocation = fullfile('D:\xyModelGEM\xyModelGEMAdapter.m');
ModelAdapterManager.setDefault(adapterLocation);

model = importModel('D:\xyModelGEM\models\iMS508_2.xml');
[ecModel, noUniprot] = makeEcModel(model);

saveEcModel(ecModel, 'ecModel.yml');
saveEcModel(ecModel, 'stage2ecModel.yml')

